name: gestao_despesas
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Gerenciamento de estado
  flutter_riverpod: ^2.5.0

  # Utilitários
  uuid: ^4.2.1
  fl_chart: ^0.63.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Gerador de código
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
